version: '3.8'

services:
    db:
      image: mysql:latest
      container_name: mysql-db   
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=desafio_mettech
      ports:
        - "3306:3306"
      restart: always
      
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: my-php-myadmin
      ports:
        - "8082:80"
      restart: always
        
      depends_on:
        - db
      environment:
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: 123456
    
    apilancamento:                        
      image: api-lancamento              
      container_name: api-lancamento-app  
      build:      
        context: .                         
        dockerfile: Dockerfile              
      ports:
        - "8080:8080"                       
      restart: always
      depends_on:                          
        - db                               
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/desafio_mettech?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: 123456
   